### ISSUE TITLE
v8 list

### ISSUE THREAD

**Issue by bmeck** [nodejs/llnode#1]
it would be nice to see the source of JS function frames during `bt`.

IE:
```
> bt
#1 ... foo.js:2:3
> list
console.log(2)
console.log(3)
```

where foo.js is
```javascript
console.log(1)
console.log(2)
console.log(3)
```

**Comment by indutny** [comment]
Thanks!

More description (in case if anyone will be interested in contributing this).

Workflow:

* `v8 list` should list all lines (`lldb` prints 7, but we don't have particular line information) of the source of the function from the current frame (frame may be selected with `f <number>`, as it regularly is in `lldb`)
* `v8 list <line-num>` should list 10 lines around `<line-num>` of the function from the current frame
* `v8 list <function-pointer>:<line-num>` should take source from the `<function-pointer>` and print 10 lines around `<line-num>`.

Now comes gritty details:

First of all you will need to create `ListCmd` in `llnode.h`. It should look like https://github.com/indutny/llnode/blob/03da80e6d308a69775d0862d6dbf7cd9fb0f2fe7/src/llnode.h#L19-L32 .

Now you will need to write `ListCmd::DoExecute` in `llnode.cc`, like this: https://github.com/indutny/llnode/blob/03da80e6d308a69775d0862d6dbf7cd9fb0f2fe7/src/llnode.cc#L14-L73 . Note `GetSelectedFrame` usage, you will need this to pick up the current frame. Don't forget to to call `GetSymbol()` to make sure that you are not dealing with C++ frame! Ideally, `ListCmd` should execute regular `list` if it meets C++ frame.

Next, you will need to add `JSFunction Function()` method to the `JSFrame` in `llv8.cc` and `llv8.h` (https://github.com/indutny/llnode/blob/03da80e6d308a69775d0862d6dbf7cd9fb0f2fe7/src/llv8.h#L337-L347). The body of this method should do something like this: https://github.com/indutny/llnode/blob/03da80e6d308a69775d0862d6dbf7cd9fb0f2fe7/src/llv8.cc#L176-L185 , probably checking the `marker` and `context` too. Basically, it should error if the frame does not represent any JS function.

You will use `frame.Function()` in `ListCmd` in `llnode.cc`. `function.Info()` will give you `SharedInfo`, `info.GetScript()` will give you a `Script`. `script.Source()` will give you a `String`. Now, `function.StartPosition()` will give you a starting position of function, and you will need to add `EndPosition` ;)

Hopefully this helps!

**Comment by bmeck** [comment]
I can try and add this

**Comment by indutny** [comment]
@bmeck if I understand it correctly we still don't have a way to dump the source of particular function using it's address. Is it the case?

**Comment by bmeck** [comment]
not right now, was waiting on code map since address could refer to a code block or a v8 heap object

**Comment by hhellyer** [comment]
@indutny v8 inspect -s  will dump the source of function given it's address. Does that mean we can close this now?

**Comment by indutny** [comment]
@hhellyer yeah, I don't see any need in these extras anymore. Thanks!
