### ISSUE TITLE
findjsinstances is not completely finished

### ISSUE THREAD

**Issue by gentlejo** [nodejs/llnode#112]
OS: RHEL7 
llnode version: 3.4.5

When I run findjsinstances command, it is not completely finished if its item is over about 100,000.

    (lldb) v8 findjsobjects
    ....
      24126    1338176 Object
      26602     854744 (Array)
     110907    2336544 (String)
    ....

    (lldb) v8 findjsinstances (String)
    killed (or Bus error)

If I upgrade to 3.9.x or 4.x, it shows better performance? Or what should I do to get result of big items?

**Comment by bnoordhuis** [comment]
I suspect it's either some kind of memory corruption or that llnode simply runs out of memory or stack space.

Is there an easy way for me to reproduce, like a small test script I can run against a particular version of node?

**Comment by hhellyer** [comment]
@gentlejo - I've landed a fix for external strings, could you verify by installing from the master version?
`npm install -g nodejs/llnode`
I think external strings are likely to have been your issue as well but it's possible v8 has another type of string we aren't handling properly! If you can verify the fix that would be great, if it's not fixed please re-open this.

**Comment by gentlejo** [comment]
@hhellyer Oh so sorry for replying late. It was fixed! Thank you! 👍
