### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by langhuihui** [nodejs/llnode#127]
`
[root@localhost ~]# npm i -g llnode

> llnode@1.6.1 preinstall /usr/local/lib/node_modules/llnode
> node scripts/configure.js

/usr/local/lib/node_modules/llnode/scripts/configure.js:3
const os = require('os');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
`

**Comment by bnoordhuis** [comment]
With what version of node.js (`node -v`) is that?

**Comment by langhuihui** [comment]
8.3.0

**Comment by bnoordhuis** [comment]
It can't be, the line numbers in the stack trace don't match up.  You probably have an old node binary on your path somewhere.

**Comment by langhuihui** [comment]
you are right!
`proc/irq/2/node
/proc/irq/1/node
/proc/irq/0/node
/sys/bus/node
/sys/devices/system/node
/root/.node-gyp/8.3.0/include/node
/root/node
/usr/bin/node
/usr/share/node
/usr/local/bin/node
/usr/local/include/node
/usr/local/share/doc/node
/usr/local/n/versions/node
/usr/local/n/versions/node/8.3.0/bin/node
/usr/local/n/versions/node/8.3.0/include/node
/usr/local/n/versions/node/8.3.0/share/doc/node
/usr/local/n/versions/node/8.4.0/bin/node
/usr/local/n/versions/node/8.4.0/include/node
/usr/local/n/versions/node/8.4.0/share/doc/node
[root@localhost llnode]# /usr/bin/node -v
v0.10.46
[root@localhost llnode]# node -v
v8.4.0
[root@localhost llnode]#
`
