### ISSUE TITLE
run llnode error

### ISSUE THREAD

**Issue by langhuihui** [nodejs/llnode#132]
Process 24832 launched: '/usr/local/bin/node' (x86_64)
buffer.js:563
      if (encoding === 'utf-8') return buf.utf8Slice(start, end);
                                           ^

Error: "toString()" failed
    at stringSlice (buffer.js:563:44)
    at Buffer.toString (buffer.js:629:10)
    at Object.fs.readFileSync (fs.js:603:41)
    at startup (bootstrap_node.js:152:27)
    at bootstrap_node.js:598:3
Process 24832 exited with status = 1 (0x00000001)

**Comment by joyeecheung** [comment]
Looks like Node can not read your file as utf8 strings. Can you share the script and the version of Node that you are using? Does this error come up when you run the script without using lldb?

**Comment by langhuihui** [comment]
Node version:8.4.0. Even if running llnode -- node -c core.24338.
Run the script very well without using lldb

**Comment by joyeecheung** [comment]
@langhuihui The command should be `llnode node -c core.24338` (without `--`). If you put `--` before `node`, then it would be equivalent to running `node -c core.24338` with lldb. You will see the same error when you run `node -c core.24338` directly.

**Comment by langhuihui** [comment]
thank u
