### ISSUE TITLE
Failed to load XXX

### ISSUE THREAD

**Issue by langhuihui** [nodejs/llnode#137]
on windows
#17 
I opened the debugmode
```
Failed to load SmiTag
Failed to load SmiTagMask
Failed to load SmiShiftSize
Failed to load HeapObjectTag
Failed to load HeapObjectTagMask
Failed to load class_HeapObject__map__Map
```

**Comment by bnoordhuis** [comment]
No surprise, node.exe doesn't have the postmortem metadata, it's only available in the UNIX binaries: https://github.com/nodejs/node/blob/v8.6.0/common.gypi#L47

I'll close this out and circle back to #17.
