### ISSUE TITLE
Detailed findjsobjects output

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#149]
I was looking at the mdb_v8 output, and they have quite a different output for this command. For example, instead of grouping objects only by type or by constructor name,  they also use the object properties and array indexes to aggregate them. They also have three other columns (Representative Object, Number of Properties and list of Properties) in their output, which looks like this:

```
OBJECT #OBJECTS   #PROPS CONSTRUCTOR: PROPS
   │       │         │        │         │
   │       │         │        │         └───> The first few properties for those
   │       │         │        │               objects
   │       │         │        │
   │       │         │        └─────────────> Name of this type's constructor
   │       │         │
   │       │         └──────────────────────> Number of properties + array 
   │       │                                  indexes for those objects
   │       │                                  
   │       └────────────────────────────────> Number of instances
   │       
   └────────────────────────────────────────> Representative object (address to 
                                              one sample object from this group)
   
   
```

I developed a prototype for a detailed version of findjsobjects, which is available [here (branch feature/findjsobjects-detailed-output)](https://github.com/mmarchini/llnode) and can be used with `v8 findjsobjects --detailed`. There's also a [demo](https://asciinema.org/a/147794) on Asciinema.

In this prototype, I added three new columns (Representative Object, Number of Properties and Array Size), and added the first three properties to the objects group name (last column). Objects are grouped by constructor name + properties + array size.

If you're interested I can create a PR with those changes. 
I'm also opened to suggestions on this.

**Comment by bnoordhuis** [comment]
Nice!

I can think of a few improvements (print length rather than "length" for arrays, make symbol properties display nicely, use an object's `@@toStringTag` if there is one, etc.) but this is a good start.

**Comment by mmarchini** [comment]
Thanks for the feedback!

I'll take a look into that this week

**Comment by mmarchini** [comment]
> print length rather than "length" for arrays

Did you mean using `JSObject::GetArrayLength()` instead of `JSArray::Length`?

> make symbol properties display nicely, use an object's @@toStringTag if there is one

I did some digging into that but seems like llnode doesn't support Symbol properties or `@@toStringTag` yet (I'll open another issue to investigate it in the future). I like the idea of using `@@toStringTag` when it's present, but what should we do when `@@toStringTag` is a function? For example:

```javascript
class Foo {
  constructor(yes) {
    this.bar = "foo bar";
  }
  get [Symbol.toStringTag]() {
    return "[ Foo " + this.bar + " ]";
  }
}
```

**Comment by bnoordhuis** [comment]
Sorry, I didn't make that clear.  In your demo it prints "(Array): length" which is factually correct (arrays have a "length" property) but arguably less useful than the actual numeric length. :-)

> what should we do when @@toStringTag is a function?

Nothing.  The idea is to use it when it's  a simple data property, or use something else when it's not.

**Comment by mmarchini** [comment]
> Sorry, I didn't make that clear. In your demo it prints "(Array): length" which is factually correct (arrays have a "length" property) but arguably less useful than the actual numeric length. :-)

Got it now :)
I agree, the actual numeric length is more useful, but this information is already present in the 5th column:

1. Column to display length + keep length property

```
Repr. Obj. Instances Total Size Properties Array Size Name
---------- --------- ---------- ---------- ---------- ----
3a123fdc4e         1         24          1          7 (Array): length
```

Here are a few suggestions for alternative ways to display the numeric length (showing or hiding the `length` property):

2. Column to display length + hide length property

```
Repr. Obj. Instances Total Size Properties Array Size Name
---------- --------- ---------- ---------- ---------- ----
3a123fdc4e         1         24          0          7 (Array)
```

3. Display the length after constructor name + display length property

```
Repr. Obj. Instances Total Size Properties Name
---------- --------- ---------- ---------- ----
3a123fdc4e         1         24          1 (Array)[7]: length
```

4. Display the length after constructor name + hide length property

```
Repr. Obj. Instances Total Size Properties Name
---------- --------- ---------- ---------- ----
3a123fdc4e         1         24          1 (Array)[7]
```

Either option is fine for me. I'm just not too keen to options 2 and 4 because other objects (besides `Array`) can also have a length property (like `Table` on the demo). They can also have a numeric length without the `length` property (like `SafeMap` on the demo).

**Comment by bnoordhuis** [comment]
Oh, I missed that in the demo.  Perhaps show the first few elements when it's a JSArray?

(I'm saying that like it's easy.  I realize it adds quite a bit of special-casing.)
