### ISSUE TITLE
Current stable?

### ISSUE THREAD

**Issue by ilovezfs** [nodejs/llnode#166]
https://github.com/nodejs/llnode/releases
shows v1.6.3 and v1.6.2

But https://github.com/nodejs/llnode/releases/latest
still points to v1.6.2

**Comment by joyeecheung** [comment]
Thanks for reporting. This is now fixed. https://github.com/nodejs/llnode/releases/tag/v1.6.3

**Comment by ilovezfs** [comment]
Thanks @joyeecheung! Voilà: https://github.com/Homebrew/homebrew-core/pull/22892
