### ISSUE TITLE
meta: logo for the project

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#169]
Hey!

Wouldn't it be cool if llnode had a logo? Our designer (@raissasf) came up with a few ideas for it!

1.
![logo1_500px](https://user-images.githubusercontent.com/4048656/36921826-8440c07e-1e44-11e8-85ad-8c8415867256.png)

2.
![logo2_500px](https://user-images.githubusercontent.com/4048656/36921827-845fc776-1e44-11e8-922e-44b0a0df66cc.png)

3.
![logo3_500px](https://user-images.githubusercontent.com/4048656/36921828-84822424-1e44-11e8-88e9-d22af257acc2.png)

What do you think?

**Comment by indutny** [comment]
I love it! Great work, @raissasf!

**Comment by joyeecheung** [comment]
Nice work!

(Can we display ascii art in something like `v8 about`? XD)

**Comment by mmarchini** [comment]
Which one do you prefer? I can open a PR to add it to our readme

> (Can we display ascii art in something like v8 about? XD)

I think we can, yeah XD

**Comment by joyeecheung** [comment]
Closed via https://github.com/nodejs/llnode/pull/171, thanks!
