### ISSUE TITLE
make install-osx not working (./out/Release/llnode.dylib: No such file or directory)

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#173]
Not sure if there's something wrong on my machine or if the installer is actually broken. Anyone else got this error? If so I can submit a fix. 

```bash
$ make install-osx
mkdir -p ~/Library/Application\ Support/LLDB/PlugIns/
cp -rf ./out/Release/llnode.dylib \
		~/Library/Application\ Support/LLDB/PlugIns/
cp: ./out/Release/llnode.dylib: No such file or directory
make: *** [install-osx] Error 1
```

**Comment by joyeecheung** [comment]
I think it should copy the dylib from the project directory because cleanup.js now moves `./out/Release/llnode.dylib` there?

**Comment by mmarchini** [comment]
Yeah, I fixed it locally but wasn't sure if it was happening just to me, so I decided to check before submitting the fix. Just tested in a Linux machine and `make install-linux` is also broken.

PR with the fix: https://github.com/nodejs/llnode/pull/174
