### ISSUE TITLE
Color output for commands

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#179]
While trying to come up with a comprehensible output format for https://github.com/nodejs/llnode/issues/115, I decided to play with colors in llnode commands outputs:

[![asciicast](https://asciinema.org/a/171606.png)](https://asciinema.org/a/171606)

Not entirely sure if this is something we want to have on llnode since we'll need to detect if the terminal supports color (I have no idea how to do that), but if we decide to have it I can open a PR with it.

**Comment by joyeecheung** [comment]
We can use an environment variable or a command line flag to control the colors (for example to work around tests or other cases where we need to redirect the output to a file)

**Comment by joyeecheung** [comment]
BTW I have this when I needed to write the output of a command to a file when it's too long to read in the terminal (e.g. the result of `v8 findjsinstance`)

`~/.lldb/to_file.py`

```python
import lldb
import sys

def to_file(debugger, command, result, dict):
    # Change the output file to a path/name of your choice
    f = open("/tmp/temp-lldb-output.txt", "w")
    debugger.SetOutputFileHandle(f, True)
    # Change command to the command you want the output of
    debugger.HandleCommand(command)
    f.close()
    print >> sys.stderr, 'Written to /tmp/temp-lldb-output.txt'
    debugger.SetOutputFileHandle(sys.stdout, True)
```

`~/.lldbinit`

```
comma script import ~/.lldb/to_file.py
comma script add -f to_file.to_file to_file
```

**Comment by mmarchini** [comment]
Ohh, nice script! I usually do `lldb node -c core -b -o "v8 findjsinstances" > output.txt`, but I need to quit lldb to use this :/.

I was thinking: we could have something like `v8 settings set color on` (off by default), and then use the llnode script to determine if the terminal is color-friendly. If it is, turn on color with `--one-line "v8 settings set color on"` before starting lldb. What do you think?

**Comment by joyeecheung** [comment]
@mmarchini SGTM

**Comment by gibfahn** [comment]
>We can use an environment variable or a command line flag to control the colors (for example to work around tests or other cases where we need to redirect the output to a file)

If we do this (which I think we should) I think the standard is to set `--color=auto`, which outputs color if the stdout/stderr is a tty, and not otherwise. Then you can have always or never as options. That seems to be what other programs I've used tend to have.

**Comment by Drieger** [comment]
I started working on a prototype, using the [rang](https://agauniyal.github.io/rang/) library. Any any thoughts and ideas are  welcome.

Current work: https://github.com/nodejs/llnode/compare/master...Drieger:start_colorization
