### ISSUE TITLE
Drop support for the original gyp?

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/llnode#181]
I was trying to merge `gyp_llnode` into `scripts/configure.js` and make `llnode.gyp` just `binding.gyp` (also in preparation for https://github.com/nodejs/llnode/pull/147). I noticed that it would be easier if we just drop support for the original gyp and only supports node-gyp, which handles a lot of configuration done by `gyp_llnode`.

Note that on master, cloning`https://chromium.googlesource.com/external/gyp.git` to `tools/gyp` and use that to build llnode does not actually work at the moment, and it always gets deleted and relinked to the gyp in the node-gyp installation. (the first commit in https://github.com/nodejs/llnode/pull/177 can fix that though). There are no issues for that so I don't think anyone actually uses the original gyp anymore?

**Comment by joyeecheung** [comment]
cc @indutny @bnoordhuis @hhellyer  what do you think?

**Comment by bnoordhuis** [comment]
I'm fine with that.

**Comment by indutny** [comment]
:+1:
