### ISSUE TITLE
meta: supported Node.js versions

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#190]
Now that Node.js v4.x is EOL, should we drop support for it? If we do, should this be a major llnode release?

IMO we should:
* Do a best-effort to support all active Node.js release lines, and we should drop support for EOL versions. 
* Do a major release every time we add/drop support to a release line.
* Document which versions Node.js each llnode major supports. This could be a table in our README.

WDYT?

**Comment by bnoordhuis** [comment]
Agreed on all 3 points.

**Comment by joyeecheung** [comment]
SGTM

**Comment by cjihrig** [comment]
SGTM

**Comment by mmarchini** [comment]
> Do a best-effort to support all active Node.js release lines, and we should drop support for EOL versions.

We've been doing that for a while

> Do a major release every time we add/drop support to a release line.

Same

> Document which versions Node.js each llnode major supports. This could be a table in our README.

We don't have an explicit table anymore, but https://github.com/nodejs/llnode#prerequisites-official-active-nodejs-version states we only support active versions. I'll close this issue, but if anyone wants to add a table feel free to do so.
