### ISSUE TITLE
meta: nominate @mmarchini to be a collaborator 

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/llnode#191]
@mmarchini is a Node.js core collaborator and member of the diagnostics WG and has been doing a lot of work on this project lately. He does not yet have collaborator access to this project though, so I would like to nominate him to be a collaborator.

**Comment by cjihrig** [comment]
I'm not even really sure if I'm considered an llnode collaborator, but +1 from me.

**Comment by joyeecheung** [comment]
It's been 12 days and I think that's probably enough time for a nomination to go through. I've added @mmarchini to the collaborators of this repo. If anyone has different thoughts on this (although I doubt anyone will but you know, one needs to ask) please contact me privately using the email on my profile page.
