### ISSUE TITLE
'v8' is not a valid command

### ISSUE THREAD

**Issue by nanzhangren** [nodejs/llnode#213]
After install the llnode by **npm install llnode**, I try to run the v8 in lldb, but the error below caught me:
_(lldb) v8
error: 'v8' is not a valid command.
error: Unrecognized command 'v8'._

**Comment by joyeecheung** [comment]
Did you run `npm install llnode`, or `npm install -g llnode`? You need to install it globally to use the `llnode` shortcut, otherwise you need to follow [other instructions](https://github.com/nodejs/llnode#loading-the-llnode-plugin) in the README to load it into lldb.

**Comment by nanzhangren** [comment]
My mistake, I just have not loaded llbnode to lldb. Thanks!

**Comment by anil9t5** [comment]
I have forked the repo and wanted to use the forked version of llnode with lldb.

**Comment by joyeecheung** [comment]
cd into the llnode directory and do an npm link should do the trick.

**Comment by anil9t5** [comment]
> cd into the llnode directory and do an `npm link` should do the trick.

thanks that worked, I got an issue so first I had to do "npm install --unsafe-perm" and then I was able to do "npm link"
