### ISSUE TITLE
Cap the result of `v8 findjsinstances`

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#230]
The result from `v8 findjsinstances` can be massive, which makes output slow and also harder to read.

We could cap the number of objects returned by findjsinstances to 10 for example, and let the user ask for more objects if they want, either by flags -n/-h[ead]/-t[ail], or by calling the command again (I think that's how mdb_v8 works).

Example:

```
(llnode) v8 findjsinstances -d Lero
0x00000548a34200e1:<Object: Lero properties {
    .constructor=<unknown field type>}>
0x00000548a3420589:<Object: Lero properties {
    .lala=0x00000548a34205e9:<Object: Object>}>
0x00000548a3420659:<Object: Lero properties {
    .lala=0x00000548a34206b9:<Object: Object>}>
0x00000548a3420589:<Object: Lero properties {
    .lala=0x00000548a34205e9:<Object: Object>}>
0x00000548a3420659:<Object: Lero properties {
    .lala=0x00000548a34206b9:<Object: Object>}>
0x00000548a3420589:<Object: Lero properties {
    .lala=0x00000548a34205e9:<Object: Object>}>
0x00000548a3420659:<Object: Lero properties {
    .lala=0x00000548a34206b9:<Object: Object>}>
0x00000548a3420589:<Object: Lero properties {
    .lala=0x00000548a34205e9:<Object: Object>}>
0x00000548a3420659:<Object: Lero properties {
    .lala=0x00000548a34206b9:<Object: Object>}>
0x00000548a3420589:<Object: Lero properties {
    .lala=0x00000548a34205e9:<Object: Object>}>
...
(Showing 10 of 62903)
```

**Comment by joyeecheung** [comment]
Is it possible to do a less-like pagination in lldb?

**Comment by mmarchini** [comment]
I don't think so, although it does have a simple paginate mechanism (I just don't remember which command uses it). If we want something more sophisticated, we'll probably have to write a CLI tool on top of llnode's API (which I have thought about several times).

**Comment by joyeecheung** [comment]
I believe flags would be easier to implement. Paginating with repeat calls seems less user-friendly since it's easier to get lost

**Comment by mmarchini** [comment]
Implemented on https://github.com/nodejs/llnode/pull/235
