### ISSUE TITLE
Give npm collaborator access to @mmarchini ?

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/llnode#234]
As the title says.

**Comment by cjihrig** [comment]
Makes sense to me.

**Comment by cjihrig** [comment]
Not to sidetrack this issue, but do rnchamberlain and hhellyer still require npm publish rights?

**Comment by joyeecheung** [comment]
Oh right I think I forgot to mention other people who have npm collaborator access right now, sorry. So here it is: @rnchamberlain @hhellyer

**Comment by joyeecheung** [comment]
I think we have left this issue open for enough amount of time.

Judging from https://www.npmjs.com/package/linux-perf I invited @mmarchini to the npm collaborators (let me know if I messed up).

**Comment by mmarchini** [comment]
I think it worked. Thanks!

**Comment by richardlau** [comment]
> 
> 
> I think we have left this issue open for enough amount of time.
> 
> Judging from https://www.npmjs.com/package/linux-perf I invited @mmarchini to the npm collaborators (let me know if I messed up).

Wasn't this for https://www.npmjs.com/package/llnode?

**Comment by joyeecheung** [comment]
@richardlau I meant judging that the npm handle @mmarchini is releasing a package under @mmarchini 's github I believe that npm handle also belongs to @mmarchini (instead of somebody who happens to be using the same handle)

**Comment by joyeecheung** [comment]
Also I believe this can be closed now!
