### ISSUE TITLE
Simplify installation process

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#236]
I've been thinking about this for a while: llnode depending on having lldb and a compiler installed can discourage people from trying it. If we could make llnode installation work without having to install all those native dependencies (at least for most users), it would be a nice improvement.

I'm working on an npm package to provide lldb and liblldb binaries for several platforms. If it works out, we can depend on this package and use it instead the lldb installed in the system. This would allow us to have better control over the user experience as well (for example, lldb on Ubuntu is barely usable because of a [known bug](https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-4.0/+bug/1727125), which affects llnode user's experience). We can also provide flags for users who want to use a custom lldb version.

**Comment by joyeecheung** [comment]
If this package is as what I am thinking about, are we using npm as a cross-platform package manager at this point? XD

**Comment by mmarchini** [comment]
Closing since there was no progress on this, but if anyone wants to try it out feel free to do so (and we can reopen or create a new issue in that case).
