### ISSUE TITLE
llnode team on GitHub

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#241]
A GitHub team will make it easier to ping us on llnode-related issues (for example: #234 and when postmortem tests break on [nodejs/node-v8](https://github.com/nodejs/node-v8)). Might also make it easier to manage permissions for the project.

Please chime in if you'd like to be included in this GitHub team :)

@joyeecheung @indutny @cjihrig @bnoordhuis @rnchamberlain @hhellyer

**Comment by joyeecheung** [comment]
I am interested

**Comment by joyeecheung** [comment]
@mmarchini I don't think so. I've created `nodejs/llnode` under the post-mortem team and invited people listed in the OP and given it write access to this repo.
