### ISSUE TITLE
Logo missing on npm page

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#251]
![image](https://user-images.githubusercontent.com/4048656/49746724-ef93e900-fc88-11e8-8ea5-b7b99343c4e8.png)

**Comment by anil9t5** [comment]
I was looking to work on fixing this. I am not sure where to edit this.

**Comment by anil9t5** [comment]
@mmarchini I wanted to look into this issue, but I don't know where to make the changes.

**Comment by mmarchini** [comment]
I don't remember anyone fixing it, but it's working, so :woman_shrugging: 

![image](https://user-images.githubusercontent.com/4048656/89365285-205c3980-d689-11ea-8172-1123c2979bff.png)
