### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by zhengboah** [nodejs/llnode#254]
node: 8.9.0

core size: 1.2G

> (llnode) v8 findjsobjects
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Stack dump: 
   0.	HandleCommand(command = "v8 findjsobjects")

what is the reason about the above?

**Comment by mmarchini** [comment]
Hi @zhengboah,

Thank you for filing this issue. `std::bad_alloc` can happen for a number of reasons (for example, out of bound memory access). This seems like a llnode bug.

Can you share a little more information?

**llnode version**: ??
**Operating System**: ??

Also, it might be worth trying to run llnode in debug mode. Install a debug build of llnode with `npm install -g llnode --debug` (the debug build might give us a more complete stack dump) and run it with `LLNODE_DEBUG=1 llnode`. Please share the complete output, if possible.

**Comment by zhengboah** [comment]
**llnode version**: 4.0.0
**OS**: Ubuntu 16.04.2 LTS


I tried again with debug , and the output is below:

> (llnode) v8 findjsobjects
[llv8] Failed to find symbol v8dbg_class_Map__instance_type__uint16_t
[llv8] Failed to load constant class_Map__instance_type__uint16_t, default to -1
[llv8] Failed to find symbol v8dbg_FirstContextType
[llv8] Failed to load constant FirstContextType, default to -1
[llv8] Failed to find symbol v8dbg_LastContextType
[llv8] Failed to load constant LastContextType, default to -1
[llv8] Failed to find symbol v8dbg_type_JSError__JS_ERROR_TYPE
[llv8] Failed to load constant type_JSError__JS_ERROR_TYPE, default to -1
[llv8] Failed to find symbol v8dbg_type_ScopeInfo__SCOPE_INFO_TYPE
[llv8] Failed to load constant type_ScopeInfo__SCOPE_INFO_TYPE, default to -1
[llv8] Failed to find symbol v8dbg_prop_type_mask
[llv8] Failed to load constant prop_type_mask, default to -1
[llv8] Failed to find symbol v8dbg_class_SharedFunctionInfo__name_or_scope_info__Object
[llv8] Failed to load constant class_SharedFunctionInfo__name_or_scope_info__Object, default to -1
[llv8] Failed to find symbol v8dbg_class_SharedFunctionInfo__inferred_name__String
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
[llv8] Not object and not smi
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Stack dump:
> 0.	HandleCommand(command = "v8 findjsobjects")


thanks!

**Comment by robey** [comment]
This happens with every corefile I try, even if it's only 700MB.

Does llnode work for anyone else?

**Comment by alexnum** [comment]
Do you have enough space left on your "/" partition?

**Comment by mmarchini** [comment]
This issue refers to an old llnode version as well as a EOL Node.js version, so I'll go ahead and close it. Furthermore, we fixed some `std::bad_alloc` errors in recent versions. If this issue occurs for someone else, please file a new issue.
