### ISSUE TITLE
Use GitHub actions to test instead of Travis?

### ISSUE THREAD

**Issue by mmarchini** [nodejs/llnode#312]
Travis takes ~30 minutes to run due to low palatalization of jobs (3 concurrent jobs, and they usually take a few minutes to start). GitHub Actions limit seems to be 20. Might be worth giving it a try.

**Comment by richardlau** [comment]
re. the `good first issue` label -- it seems from [similar PRs to use GitHub actions](https://github.com/nodejs/remark-preset-lint-node/pull/24#issuecomment-534923604) in other repos on the org the Actions can only be triggered on the PR if the branch is in the same repo (i.e. from someone with write access).

**Comment by mmarchini** [comment]
Seems like they fixed it though:

> A workflow that specifies a pull_request as the event will always run in the repository that contains that pull_request.  So when I raise a pull_request to the upstream repo from a fork of that repo the workflow run will be in that upstream repo.

Ref: https://github.community/t5/GitHub-Actions/Run-a-GitHub-action-on-pull-request-for-PR-opened-from-a-forked/m-p/31147/highlight/true#M690

**Comment by mmarchini** [comment]
Also, this pull request https://github.com/nodejs/remark-preset-lint-node/pull/21 is from a fork, and the action ran successfully, so it should work :)

**Comment by richardlau** [comment]
I mean the initial PR that adds the actions. Once added they run for PR's from other forks as expected. See https://github.com/nodejs/remark-preset-lint-node/pull/24#issuecomment-534923604 and subsequent replies.

**Comment by mmarchini** [comment]
Ah, gotcha. Removing the `good first issue` label then.
