### ISSUE TITLE
Post-mortem test suite

### ISSUE THREAD

**Issue by gibfahn** [nodejs/llnode#37]
I'd like to set up tests running llnode against coredumps. I've noticed that the current suite only tests attaching to a running process, and I'd like to extend it to run the same tests on an aborted process (I think the simplest method would be to run with `--abort-on-uncaught-exception` and then run the existing suite on the dump). 

Does anyone have any views on how this should look (or how this should be implemented)?

**Comment by rnchamberlain** [comment]
+1 for this, I would suggest testing core dumps from segv crash and out of memory scenarios as well as uncaught exception.

**Comment by indutny** [comment]
Sounds interesting indeed!

It'll most likely require a custom CI infrastructure with the core dumps enabled. cc @nodejs/jenkins-admins and @TheAlphaNerd  maybe?

**Comment by indutny** [comment]
We have one test case that checks core dumps on OS X at the moment. It would be great to have something broader for other unixes too.

**Comment by bnoordhuis** [comment]
@gibfahn Are you still working on this?

**Comment by gibfahn** [comment]
>@gibfahn Are you still working on this?

First step is getting tests in CI with https://github.com/nodejs/build/issues/777.

**Comment by mmarchini** [comment]
Testing on TravisCI is working, and the Build WG is working to create a llnode job on Jenkins (https://github.com/nodejs/build/pull/1025). Since we have a llnode test suite working right now and there's a tracking issue to create the Jenkins job, I'll close this, but feel free to reopen.
