### ISSUE TITLE
llnode - installation problem

### ISSUE THREAD

**Issue by RumenStoev** [nodejs/llnode#378]
> llnode@3.2.0 preinstall /home/rumen/.npm-global/lib/node_modules/llnode
> node scripts/configure.js

Build dir is: /home/rumen/.npm-global/lib/node_modules/llnode
Looking for lldb executable...
Found lldb executable /usr/bin/lldb

Reading lldb version...
Installing llnode for /usr/bin/lldb, lldb version 10.0

Looking for llvm-config for lldb 10.0...
No llvm-config found

Looking for headers for lldb 10.0...
Found lldb headers in /usr/include

Looking for shared libraries for lldb 10.0...
From ldd: /usr/bin/lldb loads /lib/x86_64-linux-gnu/liblldb-10.so.1
Found liblldb-10.so in /lib/x86_64-linux-gnu
Writing config.gypi:
{
  "variables": {
    "lldb_lib_dir%": "/lib/x86_64-linux-gnu",
    "lldb_lib%": "lldb-10",
    "lldb_include_dir%": "/usr/include",
    "build_addon": "false",
    "coverage": "false"
  }
}
Writing llnode.js shortcut to /home/rumen/.npm-global/lib/node_modules/llnode/llnode.js
/home/rumen/.npm-global/bin/llnode -> /home/rumen/.npm-global/lib/node_modules/llnode/llnode.js

> llnode@3.2.0 install /home/rumen/.npm-global/lib/node_modules/llnode
> node scripts/install.js

make: Entering directory '/home/rumen/.npm-global/lib/node_modules/llnode/build'
  CXX(target) Release/obj.target/plugin/src/constants.o
  CXX(target) Release/obj.target/plugin/src/error.o
  CXX(target) Release/obj.target/plugin/src/llnode.o
  CXX(target) Release/obj.target/plugin/src/llv8.o
../src/llv8.cc:736:36: warning: trigraph ??) ignored, use -trigraphs to enable [-Wtrigraphs]
  736 |   RETURN_IF_INVALID(name, "Symbol(???)");
      |                                     
  CXX(target) Release/obj.target/plugin/src/llv8-constants.o
  CXX(target) Release/obj.target/plugin/src/llscan.o
../src/llscan.cc: In member function ‘virtual bool llnode::FindReferencesCmd::DoExecute(lldb::SBDebugger, char**, lldb::SBCommandReturnObject&)’:
../src/llscan.cc:568:22: warning: ‘scanner’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  568 |     ScanForReferences(scanner);
      |     ~~~~~~~~~~~~~~~~~^~~~~~~~~
  CXX(target) Release/obj.target/plugin/src/printer.o
../src/printer.cc: In member function ‘std::string llnode::Printer::Stringify(T, llnode::Error&) [with T = llnode::v8::JSArrayBuffer; Actual = llnode::v8::JSArrayBuffer; std::string = std::__cxx11::basic_string<char>]’:
../src/printer.cc:371:26: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
  371 |       if (display_length < *byte_length) {
      |           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
../src/printer.cc: In member function ‘std::string llnode::Printer::Stringify(T, llnode::Error&) [with T = llnode::v8::JSTypedArray; Actual = llnode::v8::JSTypedArray; std::string = std::__cxx11::basic_string<char>]’:
../src/printer.cc:436:24: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
  436 |     if (display_length < *byte_length) {
      |         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
../src/printer.cc: In member function ‘std::string llnode::Printer::Stringify(T, llnode::Error&) [with T = llnode::v8::Map; Actual = llnode::v8::Map]’:
../src/printer.cc:462:15: warning: control reaches end of non-void function [-Wreturn-type]
  462 |   std::string in_object_properties_or_constructor;
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/plugin/src/node.o
  CXX(target) Release/obj.target/plugin/src/node-constants.o
  CXX(target) Release/obj.target/plugin/src/settings.o
  SOLINK(target) Release/obj.target/plugin.so
  COPY Release/plugin.so
make: Leaving directory '/home/rumen/.npm-global/lib/node_modules/llnode/build'

> llnode@3.2.0 postinstall /home/rumen/.npm-global/lib/node_modules/llnode
> node scripts/cleanup.js

Moving /home/rumen/.npm-global/lib/node_modules/llnode/build/Release/plugin.so to /home/rumen/.npm-global/lib/node_modules/llnode/llnode.so

llnode plugin installed, load in lldb with:

(lldb) plugin load /home/rumen/.npm-global/lib/node_modules/llnode/llnode.so

or copy plugin to lldb system plugin directory
see https://github.com/nodejs/llnode

The version is Ubuntu 20.04! But connot run the llnode?

What should I do next?

Thank you

**Comment by No9** [comment]
Hey @RumenStoev

Why do you think you cannot run llnode?

There are warnings in your output but the compile seems to go through ok and it looks like `llnode.so` is copied to the right place
> Moving /home/rumen/.npm-global/lib/node_modules/llnode/build/Release/plugin.so to /home/rumen/.npm-global/lib/node_modules/llnode/llnode.so

What happens when you run `llnode` on the commandline?

**Comment by No9** [comment]
This has gone stale and we have released improvements for Node.JS 14,16,18 as part of v4.0.0
Please open a new issue if you are still running into problems with the new release.
