### ISSUE TITLE
it can't run in macos, what's the problem

### ISSUE THREAD

**Issue by xiaolee55** [nodejs/llnode#381]
target create "/usr/local/bin/node" --core "core.32"
error: Don't know how to parse core file. Unsupported OS.
![image](https://user-images.githubusercontent.com/37341547/105889467-284dd280-6049-11eb-82b0-f031d3c34687.png)

**Comment by mmarchini** [comment]
where did you get the core dump from? was it from the OS X machine, from a Linux machine, or from somewhere else?

**Comment by No9** [comment]
Closing this issue as it's over a year old with no feedback.
Please feel free to re-open or raise another item if you come across this again.
