### ISSUE TITLE
Fix CI problems

### ISSUE THREAD

**Issue by oyyd** [nodejs/llnode#387]
Currently, tests always fail because: 

1. The action `mmarchini/setup-node@mirror` uses a deprecated `add-path` command

Rebasing the upstream code should fix this, like: https://github.com/mmarchini/setup-node/pull/1

2. Install `liblldb-3.9-dev` on `ubuntu-latest`, that is ubuntu-20.04 now, would fail:

![image](https://user-images.githubusercontent.com/5847587/113979193-85e77200-9877-11eb-94d3-e2a9a0720adb.png)

Don't know why but indicating `ubuntu-18.04` should fix this.

**Comment by No9** [comment]
Fixed in https://github.com/nodejs/llnode/pull/398

**Comment by No9** [comment]
#398 landed in main so closing this.
Thanks for reporting
