### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/llnode#390]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

There are a number of references to the master branch in the github workflows and docs that will also need to be changed.

**Comment by mhdawson** [comment]
@indutny @mmarchini any concerns with respect changing the primary branch to main?

**Comment by mmarchini** [comment]
Should be fine, only thing to check is the GitHub actions files (those might need some changing)

**Comment by indutny** [comment]
Yeah, sounds like automation will need to be changed indeed.

**Comment by mhdawson** [comment]
@mmarchini  went a had an update the default branch and updates the github actions and other related references. 

However, CI did not pass before, and still does not after the change. Long way of saying I don't think the rename caused the current CI issues as I tested the CI was failing before even for a simple text change, see -> https://github.com/nodejs/llnode/pull/393
