### ISSUE TITLE
ptrace: No such process.

### ISSUE THREAD

**Issue by RumenStoev** [nodejs/llnode#400]
Hello!
I use Ubuntu 20.04 and 
There are 2 problems .
1.ptrace: No such process.
You can't do that without a process to debug.
The program is not being run.
gcore: failed to create core.14317

2.Every core dump file which I created  is stuck.(is the same for every core dump)Nothing change.When I try to use llnode is not possible to inspect the "frames",but I see these frame.

Can someone help me?

**Comment by RumenStoev** [comment]
I changed the version of Node.js from v16 to v12 and everything is good

**Comment by No9** [comment]
Seems like this is resolved by dropping down a version. 
16 support is still incomplete and we will be tracking it here 
https://github.com/nodejs/llnode/issues/399
