### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by indutny** [nodejs/llnode#47]
@hhellyer @yjhjstz is there anything that you want to get in before the release? Should I cut it straight away?

**Comment by hhellyer** [comment]
I don't have anything major. I'm looking at a bug in lldb at the moment.

**Comment by yjhjstz** [comment]
just release.

**Comment by indutny** [comment]
Done in 6cb550f

**Comment by indutny** [comment]
homebrew PR: https://github.com/Homebrew/homebrew-core/pull/6930
