### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by indutny** [nodejs/llnode#49]
I think we should have one.

**Comment by rnchamberlain** [comment]
Agree. For https://github.com/nodejs/node-report we use the strongloop 'slt-release' tool for npm publishes, which does the versioning, release tag thing and maintains a change log, e.g:
https://github.com/nodejs/node-report/blob/master/CHANGES.md

To see the help:
```
npm install -g strong-tools
slt-release -h
```  
To do an npm publish and the rest:
```
npm login
git clone https://github.com/nodejs/llnode.git
cd llnode
slt-release -up 1.2.3
```

**Comment by rnchamberlain** [comment]
@indutny - @hhellyer is achieving this now with the release commits, can we close this issue?

See: https://github.com/nodejs/llnode/releases

**Comment by indutny** [comment]
👍
