### ISSUE TITLE
Internal fields

### ISSUE THREAD

**Issue by indutny** [nodejs/llnode#50]
It would be lovely if we could inspect C++ from object's internal fields. This will require some additional constants to be exported.

**Comment by hhellyer** [comment]
Agreed, we'd quite like to be able to get things like heap roots or the start and end of the various v8 heaps.
Being able to find out what callbacks are sat on the libuv event loop would also be good - though that might be part of having the heap roots since they'd be keeping objects alive.

**Comment by indutny** [comment]
While this is cool too, I actually meant: http://bespin.cz/~ondras/html/classv8_1_1Object.html#a435f68bb7ef0f64dd522c5c910682448
