### ISSUE TITLE
`v8 bt` does not work

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/llnode#55]
llnode: v1.2.0

---

OS X: 10.10.5

```
uname -a
Darwin Jeremiahs-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64 x86_64
```

---

```
lldb -v
lldb-340.4.119
```

---

XCode version: 7.2 (7C68)

**Comment by indutny** [comment]
Alright, the version of lldb is most likely a culprit. Have you installed llnode from homebrew?

**Comment by Fishrock123** [comment]
@indutny Yes:

```
brew --version
Homebrew 1.1.1-53-gc7267b1
Homebrew/homebrew-core (git revision 586c; last commit 2016-11-21)
```

**Comment by indutny** [comment]
@Fishrock123 yeah, it won't work I'm afraid. We need to figure out the way to use older lldb when building it from homebrew. Right now it picks the same for all OS X:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/llnode.rb#L22-L25

I'll see if can figure something out.

**Comment by indutny** [comment]
@Fishrock123 meanwhile you may want to use build instructions for previous lldb version:

https://github.com/nodejs/llnode/tree/142465c3dfa4b884358e8780df75583512a318aa#os-x

**Comment by indutny** [comment]
We managed to fix it with a patched homebrew formula:

```diff
diff --git a/Formula/llnode.rb b/Formula/llnode.rb
index f69abd2..d277576 100644
--- a/Formula/llnode.rb
+++ b/Formula/llnode.rb
@@ -20,8 +20,15 @@ class Llnode < Formula
   end

   resource "lldb" do
-    url "https://github.com/llvm-mirror/lldb.git",
-        :revision => "839b868e2993dcffc7fea898a1167f1cec097a82"
+    if MacOS.version >= :el_capitan
+      url "https://github.com/llvm-mirror/lldb.git",
+          :revision => "839b868e2993dcffc7fea898a1167f1cec097a82"
+    else
+      # Yosemite has way older lldb which is not available on github for some
+      # reason
+      url "http://llvm.org/svn/llvm-project/lldb/tags/RELEASE_34/final/",
+          :using => :svn
+    end
   end

   def install
```

Will include these changes in next release.

**Comment by indutny** [comment]
Opened https://github.com/Homebrew/homebrew-core/pull/7137 to gather feedback from Homebrew team.

**Comment by indutny** [comment]
Fixed by https://github.com/Homebrew/homebrew-core/commit/f399eaccf3e0db61a70af55571f3d37ce97937fe.
