### ISSUE TITLE
1.3.1

### ISSUE THREAD

**Issue by indutny** [nodejs/llnode#56]
I'd like to cut 1.3.1 to fix #55 which is a homebrew formula issue.

Any objections? @hhellyer @yjhjstz

**Comment by Fishrock123** [comment]
@indutny please do :D

**Comment by hhellyer** [comment]
Go for it.

**Comment by indutny** [comment]
@hhellyer released 1.4.0 , we had a minor change in 4459f90.

**Comment by indutny** [comment]
homebrew PR: https://github.com/Homebrew/homebrew-core/pull/7384
