### ISSUE TITLE
otool2segments does not work anymore

### ISSUE THREAD

**Issue by indutny** [nodejs/llnode#68]
```
$ ~/Code/indutny/llnode/scripts/otool2segments.py ./core
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: './core': Invalid argument.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
```

cc @hhellyer

**Comment by rnchamberlain** [comment]
Do we still need the memory segments tool? The better fix in lldb is in v3.9 and later. Maybe that's not available on Mac?

**Comment by indutny** [comment]
Its not available on Mac, at least out of the box.

**Comment by hhellyer** [comment]
I ran a quick sniff test with a random version of node and it looks ok initially. It's definitely a Mac core dump? (All mine end up in /cores named core.<pid> I'm not sure how to get them called "core" on a Mac.)
I'll try and re-create if you give me some more details:
- Which version of Node created the core? 32 or 64 bit?
- Which version of otool? (otool --version says (Apple LLVM version 8.0.0 (clang-800.0.42.1)) for me.)
- Can lldb open the core dump? (It could just be a broken core.)

**Comment by indutny** [comment]
This is definitely a core, I just moved it to `/tmp/` for unrelated reasons:

```
64 bit node.js v7.6.0
```

```
llvm-otool(1): Apple Inc. version cctools-895
Apple LLVM version 8.0.0 (clang-800.0.42.1)
```

```
$ file /tmp/core
/tmp/core: Mach-O 64-bit core x86_64
```

**Comment by indutny** [comment]
I believe that the latest `otool` internally calls `objdump` now. Here is `objdump`:

```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
  Optimized build.
  Default target: x86_64-apple-darwin16.4.0
  Host CPU: haswell
```

**Comment by hhellyer** [comment]
That's the same level of otool as me.
How big is it? I have a recollection I managed to break otool with a really massive core dump.
LLDB might be able to still open it.

**Comment by indutny** [comment]
Hm... It is around 3gb: `2876063744`. Is it too big?

**Comment by indutny** [comment]
`lldb` works with it indeed.

**Comment by hhellyer** [comment]
I just tried a test program that filled the heap and crashed. The core dump was 2889756672 and otool couldn't open it.

Not sure what to suggest, lldb has a command called "memory region". If you run:
`(lldb) memory region 0x0`
then keep repeating the command (just by hitting return) it will walk all the memory regions. Unfortunately it's not something that easy to script to.

llnode function that doesn't need to walk the heap will work but I'm guessing you have a massive dump for the same reason I do (OOM) and want to see what the heap contains.

I'm not sure what to suggest:
- llvm.org doesn't do Mac binaries so you can't just download a more recent one that has the API.
- Linux builds of lldb can't open Mac cores. (But the Mac builds can open Linux/Elf core dumps.)
- You could build a more recent lldb yourself but it does take quite a while.
- Are you able to re-create the crash on Linux and use a more recent version of lldb there?

@rnchamberlain - Any other ideas?

**Comment by rnchamberlain** [comment]
Could try reproducing the problem with a smaller heap size, to get a smaller dump (>2Gb?)?

**Comment by indutny** [comment]
Yeah, I guess so. Thank you!

**Comment by rnchamberlain** [comment]
Maybe we should add a size check and warning to otool2segments

**Comment by indutny** [comment]
Alternatively I can write a JS script that will print this info...

**Comment by indutny** [comment]
Here is the thing https://github.com/nodejs/llnode/pull/69
