### ISSUE TITLE
something wrong with exec `./gyp_llnode -Dlldb_dir=/usr/lib/llvm-3.9/` On Ubuntu

### ISSUE THREAD

**Issue by earlymeme** [nodejs/llnode#73]
```
$ ./gyp_llnode -Dlldb_dir=/usr/lib/llvm-3.9/
Traceback (most recent call last):
  File "./gyp_llnode", line 85, in <module>
    (major, minor), is_clang = compiler_version()
ValueError: need more than 1 value to unpack

```
How to solve it ? My code has been updated.

**Comment by hhellyer** [comment]
@earlymeme - That's checking the output of `cc -version`? What does that return for you? (Which C compiler are you setup to use?)

**Comment by earlymeme** [comment]
@hhellyer - I run `cc --version`, and then tell me that ```cc (Ubuntu 7-20170316-1ubuntu3) 7.0.1 20170316 (experimental) [trunk revision 246203]
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.```
I've found the experimental feature. Is that a problem?

**Comment by hhellyer** [comment]
The code for compiler_version() is:
```
def compiler_version():
  proc = subprocess.Popen(CC.split() + ['--version'], stdout=subprocess.PIPE)
  is_clang = 'clang' in proc.communicate()[0].split('\n')[0]
  proc = subprocess.Popen(CC.split() + ['-dumpversion'], stdout=subprocess.PIPE)
  version = proc.communicate()[0].split('.')
  version = map(int, version[:2])
  version = tuple(version)
  return (version, is_clang)
```
so I guess the next question is what does `cc -dumpversion` return?

**Comment by earlymeme** [comment]
hi @hhellyer - I think this is a bug...When `cc -dumpversion` is only single.And then, a error would throw from `  (major, minor), is_clang = compiler_version()`

**Comment by hhellyer** [comment]
Ok, it's just expecting a two digit version number and getting one digit. I've pushed a fix on a branch.
Could you try installing via:
`npm install hhellyer/llnode#gcc_version_fix`
If that fixes it I'll raise a pull request.

**Comment by earlymeme** [comment]
@hhellyer  It works. Thanks very much. And I see your changed code
```
  # Allow for (e.g.) gcc version 7 (not 7.0)
  version.append("0")
```

your idea is as I thought. And I had changed like yours locally. haha. :)

**Comment by indutny** [comment]
Appears to be fixed, closing!

**Comment by hhellyer** [comment]
Fixed on my branch but I haven't raised or merge the PR for the change, I'll re-open and raise the PR.

**Comment by bnoordhuis** [comment]
Closing, #78 was merged a while ago.
