### ISSUE TITLE
Creating flame graphs from core dumps taken

### ISSUE THREAD

**Issue by maziey93** [nodejs/llnode#76]
I have created a docker image that can be used by literally anyone that picks it up for debugging node in prod, I have been able to configure `llnode` , `lldb`, `perf` with help from @hhellyer  all that needs to be done is for the user to copy the generated core dump and binary of node that was running on the process into docker [see here](https://github.com/nodejs/llnode/issues/74) I'd like to take it a step further and explore the possibility of also generating flame graphs from the core dump

**Comment by hhellyer** [comment]
@maziey93 What data are you interested in graphing? Memory usage or call stack profiling?

As far as getting the data out goes you could write a custom command that dumped json output or it might be a use case for a javascript API (see issue #14).

**Comment by maziey93** [comment]
@hhellyer call stack profiling would be nice, but memory usage is more important to me right now, being that the core dump isn't exactly a running process I am not sure that using either of perf or dtrace will be of any help here.

**Comment by hhellyer** [comment]
Memory usage is a good fit, I was only wondering about profiling as that's what I usually see flame graphs used for.

We already have the v8 findjsobject/findjsinstances commands which give you counts and details for each type. If those give you the kind of data you want you could add an option to format their output as json to make them scriptable. What type of analysis are you trying to do?

**Comment by maziey93** [comment]
@hhellyer good one about memory usage I hadn't thought of it like that, so I guess call stack profiling would be the one to tackle, basically one of our app has been crashing intermittently and logs don't exactly show any error but CPU usage sometimes spikes, it went to a 100% once. it'd be nice to know what functions spend a lot of time in the call stack

**Comment by hhellyer** [comment]
@maziey93 - You probably want a profiling tool of some kind if you are looking for occaisinal CPU usage spikes but if you get a crash with an uncaught exception you can run with `--abort_on_uncaught_exception` to trigger a core file at crash time:
`> node --abort_on_uncaught_exception helloworld.js`
At that point if it isn't obvious from the stack trace what went wrong you can use llnode to look deeper into the contents of various objects to see if that helps.

(Note - I'm on vacation over easter now until next Wednesday.)

**Comment by maziey93** [comment]
@hhellyer so we pickup after easter then

**Comment by brendangregg** [comment]
Love the idea of a docker image that has llnode ready to go.

As @hhellyer said, I'd expect a profiling tool would be needed to gather the many stacks needed for a flame graph, since core dumps typically don't have many stacks (one for each thread, but that might be all unless some debug mode was enabled).

perf can sample at a timed rate for a CPU flame graph. The new stackcount tool in iovisor/bcc can trace user/kernel functions and print out frequency counted stack traces, which could be used for tracing memory allocations or page faults, for making memory flame graphs.

**Comment by maziey93** [comment]
@brendangregg I already created the docker image, you can take a look at it [here](https://github.com/maziey93/purifico) I would also like help with taking core dumps with gcore, the last time i tried to take one there was a particular error with multi-threading i couldnt resolve it, here is a [link](https://pbs.twimg.com/media/C9Opo_GXcAAFtup.png) to the error i got, i didnt want to use lldb cause then the process would have terminated.

**Comment by brendangregg** [comment]
@maziey93 ok, thanks; can you close this ticket if there's nothing to do here? Just doing cleanup.

**Comment by mmarchini** [comment]
Closing as the question has been answered. Feel free to reopen if you believe there's anything left to be discussed here.
