### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by indutny** [nodejs/llnode#88]
Would anyone mind if I'll do a release, and add it to homebrew? Given that node v8 was just released, it seems beneficial to publish the version that supports it (thanks to @bnoordhuis )

**Comment by indutny** [comment]
cc @hhellyer

**Comment by hhellyer** [comment]
@indutny - Nope that's fine, if you do brew I'll push the update to the npm.

**Comment by gibfahn** [comment]
+1 to that

**Comment by indutny** [comment]
Here is homebrew PR: https://github.com/Homebrew/homebrew-core/pull/14119

@hhellyer I'd appreciate if you could do npm release.

Thank you everyone!

**Comment by hhellyer** [comment]
@indutny I've updated the npm.

**Comment by indutny** [comment]
@hhellyer thank you!

Homebrew landed my PR. Closing this!
