### ISSUE TITLE
Reading contents of an Array/ArrayBufferView

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/llnode#89]
Hi, at the moment when doing `v8 inspect <address-of-an-array>` llnode would only print the length (and offset & backstore address) of an Array (ArrayBufferView). Are there any support for reading the elements of an Array/ArrayBufferView? Thanks.

**Comment by bnoordhuis** [comment]
Do you mean Array or ArrayBuffer?  If the latter: not at the moment.  You can take the address of the backing store and print that like you would with normal memory.

We could pretty-print ArrayBuffers but we'd need to do something sensible for large arrays, like print only the first 100 elements.

If you want to work on it, the logic is in `JSArrayBuffer::Inspect()` and `JSArrayBufferView::Inspect()` in src/llv8.cc.  Questions?  I'll try to answer them.

**Comment by joyeecheung** [comment]
@bnoordhuis Thanks for the answer, I actually meant both, but I just realized it does support arrays, I guess the arrays that I've tried somehow errorred in one of the steps of `JSObject::InspectElements` so the elements didn't show up.

I think we could do a new command for array-like objects which also takes indexes/ranges as operand? I'd be happy to work on it.

**Comment by bnoordhuis** [comment]
A flag sounds good but the default should probably be conservative for large arraybuffers because those can easily be 100s of MBs and you don't usually want to see every last byte printed.

As well, it would be nice if typed arrays printed their values as their natural types (uint8, int32, float64, etc.) instead of simply dumping out the `.buffer` property but that's a bigger undertaking.

**Comment by bnoordhuis** [comment]
@joyeecheung Just curious, were you able to make any progress on this?

**Comment by joyeecheung** [comment]
@bnoordhuis I have implemented `--array-length` for normal arrays but have not found the time to do the same for array buffers. I will open a PR for what have been done, can probably implement the other parts this weekend.

**Comment by joyeecheung** [comment]
@hhellyer The implementation for `ArrayBuffer` and `ArrayBufferView` has not been completed yet, reopening..

**Comment by hhellyer** [comment]
@joyeecheung - Ah, I suspect that's because the commit comment referenced this with "Fix", sorry about that!
