### ISSUE TITLE
findrefs performance improvement

### ISSUE THREAD

**Issue by brendangregg** [nodejs/llnode#97]
Currently findrefs has to rescan the entire heap each time. Could an index or some cache be added to improve performance of this when using it multiple times?

**Comment by bnoordhuis** [comment]
Are you experiencing performance issues?  If so, can you provide some background on the size of the core file, number of objects in it, etc.?

**Comment by brendangregg** [comment]
I'm hearing about latency second hand. Maybe the first step here is to verify that this really is an issue and provide such numbers for context, including how slow the command is. Might need #98 fixed first to really see some latency.

**Comment by bnoordhuis** [comment]
I'll close this for now.  Happy to investigate once there is some concrete data.
